import re

def resolver_escudo_local(nome_clube: str) -> str:
    if not nome_clube:
        return "/fpfs_shield.png"
    n = nome_clube.upper()
    
    if "CORINTHIANS" in n: return "/escudos/corinthians.png"
    if "PALMEIRAS" in n: return "/escudos/palmeiras.png"
    if "SANTOS" in n: return "/escudos/santos.png"
    if "S?O PAULO" in n or "SAO PAULO" in n: return "/escudos/s_o_paulo.png"
    if "JUVENTUS" in n: return "/escudos/juventus.png"
    if "MAGNU" in n or "ASF/" in n or "SOROCABANA" in n: return "/escudos/magnus.png"
    if "CAMISA 10" in n: return "/escudos/camisa_10.png"
    if "BOLA NO P?" in n or "BOLA NO PE" in n: return "/escudos/bola_no_p_.png"
    if "YPIRANGA" in n: return "/escudos/ca_ypiranga.png"
    if "MESC" in n: return "/escudos/mesc.png"
    if "BATEBOLA" in n: return "/escudos/batebola.png"
    if "TAUBAT?" in n or "TAUBATE" in n: return "/escudos/taubat_.png"
    if "UNI?O RD" in n or "UNIAO RD" in n: return "/escudos/uni_o_rd.png"
    if "SANCAETANENSE" in n or "LIGA SAN" in n or "S?O CAETANO" in n: return "/escudos/liga_s_o_caetano.png"
    if "RSFC" in n: return "/escudos/rsfc.png"
    if "SANTO ANDR?" in n or "SANTO ANDRE" in n: return "/escudos/ad_santo_andr_.png"
    if "PORTUGUESA" in n: return "/escudos/portuguesa.png"
    if "PULO" in n: return "/escudos/pulo_futsal.png"
    if "WIMPRO" in n: return "/escudos/wimpro.png"
    if "GREMETAL" in n: return "/escudos/gremetal.png"
    if "LAUSANNE" in n: return "/escudos/lausanne_paulista.png"
    if "OCIAN" in n: return "/escudos/ocian.png"
    if "AUDAX" in n or "OSASCO" in n: return "/escudos/audax.png"
    if "BATALHA" in n: return "/escudos/batalha.png"
    if "GUARULHENSE" in n: return "/escudos/guarulhense.png"
    if "INDAIATUBA" in n: return "/escudos/indaiatuba.png"
    if "ITAPEVI" in n: return "/escudos/itapevi.png"
    if "MOGI" in n: return "/escudos/mogi_das_cruzes.png"
    if "HORTOLANDIA" in n or "HORTOL?NDIA" in n: return "/escudos/hortol_ndia.png"
    if "TABUCA" in n: return "/escudos/tabuca_juniors.png"
    if "OLIMPIK" in n: return "/escudos/olimpik.png"
    if "OLE BRASIL" in n or "OL? BRASIL" in n or "PUMAS" in n: return "/escudos/pumas.png"
    
    return "/fpfs_shield.png"

def formatar_nome_clube(nome: str) -> str:
    if not nome: return ""
    n = nome.upper()
    if "CORINTHIANS" in n: return "CORINTHIANS"
    if "PALMEIRAS" in n: return "PALMEIRAS"
    if "SANTOS" in n: return "SANTOS FC"
    if "S?O PAULO" in n or "SAO PAULO" in n: return "S?O PAULO FC"
    if "JUVENTUS" in n: return "C.A. JUVENTUS"
    if "MAGNU" in n or "ASF/" in n or "SOROCABANA" in n: return "MAGNUS FUTSAL"
    if "CAMISA 10" in n: return "CAMISA 10"
    if "BOLA NO P?" in n or "BOLA NO PE" in n: return "CT BOLA NO P?"
    if "YPIRANGA" in n: return "C.A. YPIRANGA"
    if "MESC" in n: return "MESC S?O BERNARDO"
    if "BATEBOLA" in n: return "A.D. BATEBOLA"
    if "TAUBAT?" in n or "TAUBATE" in n: return "TAUBAT? FUTSAL"
    if "UNI?O RD" in n or "UNIAO RD" in n: return "UNI?O RD"
    if "SANCAETANENSE" in n or "LIGA SAN" in n: return "LIGA S?O CAETANO"
    if "RSFC" in n: return "S?O CAETANO / RSFC"
    if "SANTO ANDR?" in n or "SANTO ANDRE" in n: return "AD SANTO ANDR?"
    if "PORTUGUESA" in n: return "PORTUGUESA"
    if "PULO" in n: return "PULO CAMPINAS"
    if "WIMPRO" in n: return "WIMPRO GUARULHOS"
    if "GREMETAL" in n: return "GREMETAL SANTOS"
    if "LAUSANNE" in n: return "LAUSANNE PAULISTA"
    if "OCIAN" in n: return "OCIAN PRAIA CLUBE"
    if "AUDAX" in n or "OSASCO" in n: return "FAE / OSASCO / AUDAX"
    if "BATALHA" in n: return "BATALHA FUTSAL"
    if "GUARULHENSE" in n: return "GUARULHENSE"
    if "INDAIATUBA" in n: return "A.D. INDAIATUBA"
    if "ITAPEVI" in n: return "ITAPEVI FUTSAL"
    if "MOGI" in n: return "MOGI DAS CRUZES"
    if "HORTOLANDIA" in n or "HORTOL?NDIA" in n: return "HORTOL?NDIA"
    if "TABUCA" in n: return "C.A. TABUCA JRS"
    if "OLIMPIK" in n: return "AD OLIMPIK"
    if "OLE BRASIL" in n or "OL? BRASIL" in n: return "OL? BRASIL SOCIETY"
    return nome.strip()

print("Formatador e resolver testados com sucesso!")
